### PR TITLE
Create cs-ala

### PR DESCRIPTION
**Pull request by MultiSeptim**
A small beginning of czech translation...

### CODE REVIEW

**Comment by cooljeanius** [comment]
Hi, thanks for sending this; I'm not quite sure how to handle this considering I don't speak Czech... is there a third party we could get to help review?

**Comment by cooljeanius** [comment]
on Discord @knyghtmare points out that the file needs the `.po` file extension

**Comment by MultiSeptim** [comment]
Hi, excuse me, I am not a PC master. So, it is only a test on my part. I will send you po file via Issue.

**Comment by MultiSeptim** [comment]
And to your first question:
I am Petr Šlejhar (Septim), one of the current contributors of Czech translation team, viz [https://wiki.wesnoth.org/CzechTranslation](url). I will contact Michal (Michal Žejdl) myself when I proceed with the translation. He will check it well, dont worry.

**Comment by cooljeanius** [comment]
> And to your first question: I am Petr Šlejhar (Septim), one of the current contributors of Czech translation team, viz [https://wiki.wesnoth.org/CzechTranslation](url). I will contact Michal (Michal Žejdl) myself when I proceed with the translation. He will check it well, dont worry.

Is Michal on GitHub?

**Comment by MultiSeptim** [comment]
https://github.com/celerini

**Comment by cooljeanius** [comment]
> https://github.com/celerini

If you '@' the person they get a notification: @celerini

**Comment by MultiSeptim** [comment]
I have no problem to contact Michal.
I need incorcorate the po file (viz Issue) into your repository, to continue with work.

**Comment by cooljeanius** [comment]
ok merged and renamed; let me know if you need any further help with translation

**Pull request merged**
